Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
workflows.tedana_workflow(
    data_files,
    echo_times,
    out_dir=out_dir,
    mask=mask_file,
    prefix="sub-04570_task-rest_space-scanner",
    fittype="curvefit",
    tedpca="mdl",
    verbose=True,
    gscontrol=["mir"],
)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[3], line 1[0m
[0;32m----> 1[0m [43mworkflows[49m[38;5;241;43m.[39;49m[43mtedana_workflow[49m[43m([49m
[1;32m      2[0m [43m    [49m[43mdata_files[49m[43m,[49m
[1;32m      3[0m [43m    [49m[43mecho_times[49m[43m,[49m
[1;32m      4[0m [43m    [49m[43mout_dir[49m[38;5;241;43m=[39;49m[43mout_dir[49m[43m,[49m
[1;32m      5[0m [43m    [49m[43mmask[49m[38;5;241;43m=[39;49m[43mmask_file[49m[43m,[49m
[1;32m      6[0m [43m    [49m[43mprefix[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43msub-04570_task-rest_space-scanner[39;49m[38;5;124;43m"[39;49m[43m,[49m
[1;32m      7[0m [43m    [49m[43mfittype[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mcurvefit[39;49m[38;5;124;43m"[39;49m[43m,[49m
[1;32m      8[0m [43m    [49m[43mtedpca[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mmdl[39;49m[38;5;124;43m"[39;49m[43m,[49m
[1;32m      9[0m [43m    [49m[43mverbose[49m[38;5;241;43m=[39;49m[38;5;28;43;01mTrue[39;49;00m[43m,[49m
[1;32m     10[0m [43m    [49m[43mgscontrol[49m[38;5;241;43m=[39;49m[43m[[49m[38;5;124;43m"[39;49m[38;5;124;43mmir[39;49m[38;5;124;43m"[39;49m[43m][49m[43m,[49m
[1;32m     11[0m [43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/tedana/workflows/tedana.py:444[0m, in [0;36mtedana_workflow[0;34m(data, tes, out_dir, mask, convention, prefix, fittype, combmode, tedpca, fixed_seed, maxit, maxrestart, tedort, gscontrol, no_reports, png_cmap, verbose, low_mem, debug, quiet, t2smap, mixm, ctab, manacc)[0m
[1;32m    442[0m out_dir [38;5;241m=[39m op[38;5;241m.[39mabspath(out_dir)
[1;32m    443[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m op[38;5;241m.[39misdir(out_dir):
[0;32m--> 444[0m     [43mos[49m[38;5;241;43m.[39;49m[43mmkdir[49m[43m([49m[43mout_dir[49m[43m)[49m
[1;32m    446[0m [38;5;66;03m# boilerplate[39;00m
[1;32m    447[0m basename [38;5;241m=[39m [38;5;124m"[39m[38;5;124mreport[39m[38;5;124m"[39m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '/home/runner/work/multi-echo-data-analysis/multi-echo-data-analysis/data/multi-echo-data-analysis/data/tedana'
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/multi-echo-data-analysis/multi-echo-data-analysis/data/multi-echo-data-analysis/data/tedana'

