Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 559, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
y_vals = np.arange(5000, 10001, 100)[:, None]
x_vals = np.array([15, 30, 45, 60, 75, 90])
fig = plot_signal_scatter(x_vals, y_vals)

fig.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAssertionError[0m                            Traceback (most recent call last)
[0;32m/tmp/ipykernel_2227/396456994.py[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0my_vals[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0marange[0m[0;34m([0m[0;36m5000[0m[0;34m,[0m [0;36m10001[0m[0;34m,[0m [0;36m100[0m[0;34m)[0m[0;34m[[0m[0;34m:[0m[0;34m,[0m [0;32mNone[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0mx_vals[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0marray[0m[0;34m([0m[0;34m[[0m[0;36m15[0m[0;34m,[0m [0;36m30[0m[0;34m,[0m [0;36m45[0m[0;34m,[0m [0;36m60[0m[0;34m,[0m [0;36m75[0m[0;34m,[0m [0;36m90[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 3[0;31m [0mfig[0m [0;34m=[0m [0mplot_signal_scatter[0m[0;34m([0m[0mx_vals[0m[0;34m,[0m [0my_vals[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      4[0m [0;34m[0m[0m
[1;32m      5[0m [0mfig[0m[0;34m.[0m[0mshow[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/tmp/ipykernel_2227/1365333246.py[0m in [0;36mplot_signal_scatter[0;34m(x, y)[0m
[1;32m      6[0m     [0;32massert[0m [0mx[0m[0;34m.[0m[0mndim[0m [0;34m==[0m [0;36m1[0m[0;34m[0m[0;34m[0m[0m
[1;32m      7[0m     [0;32massert[0m [0my[0m[0;34m.[0m[0mndim[0m [0;34m==[0m [0;36m2[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 8[0;31m     [0;32massert[0m [0my[0m[0;34m.[0m[0mshape[0m[0;34m[[0m[0;36m1[0m[0;34m][0m [0;34m==[0m [0mx[0m[0;34m.[0m[0mshape[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      9[0m     [0;32massert[0m [0;36m30[0m [0;32min[0m [0mx[0m[0;34m[0m[0;34m[0m[0m
[1;32m     10[0m     [0mte30_idx[0m [0;34m=[0m [0mlist[0m[0;34m([0m[0mx[0m[0;34m)[0m[0;34m.[0m[0mindex[0m[0;34m([0m[0;36m30[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mAssertionError[0m: 
AssertionError: 

